type ProductPriceMap = Record<string, number>;
type ProductPrices = Record<string, ProductPriceMap>;

type TerritoryPriceOverrides = Partial<Record<"EFT" | "CRED", ProductPriceMap>>;

export const TERRITORY_SELLER_EMAILS = {
  tijuana: ["ventas2productoselrey@gmail.com"],
  pacificTiraMolido: [
    "ventasmztproductoselrey.com@gmail.com",
    "ventasmochisproductoselrey@gmail.com",
  ],
} as const;

const PRICE_OVERRIDES_BY_TERRITORY: Record<string, TerritoryPriceOverrides> = {
  tijuana: {
    EFT: {
      "Chiltepin Molido 50 g": 52,
      "Chiltepin Molido 20 g": 26,
      "Chiltepin Entero 30 g": 50,
      "Salsa Chiltepin El rey 195 ml": 18,
      "Salsa Especial El Rey 195 ml": 18,
      "Salsa Reina El rey 195 ml": 18,
      "Salsa Habanera El Rey 195 ml": 18,
      "Paquete El Rey": 100,
      "Molinillo El Rey 30 g": 95,
      "Tira Entero": 65,
      "Tira Molido": 60,
      "Salsa chiltepin Litro": 50,
      "Salsa Especial Litro": 50,
      "Salsa Reina Litro": 50,
      "Salsa Habanera Litro": 50,
      "Michela Mix Tamarindo": 32,
      "Michela Mix Mango": 32,
      "Michela Mix Sandia": 32,
      "Michela Mix Fuego": 32,
      "Michela Mix Picafresa": 32,
      "El Rey Mix Original": 60,
      "El Rey Mix Especial": 60,
      "Medio Kilo Chiltepin Entero": 600,
      "Habanero Molido 50 g": 40,
      "Habanero Molido 20 g": 20,
      "Molinillo Habanero 20 g": 75,
    },
    CRED: {
      "Chiltepin Molido 50 g": 52,
      "Chiltepin Molido 20 g": 26,
      "Chiltepin Entero 30 g": 50,
      "Salsa Chiltepin El rey 195 ml": 18,
      "Salsa Especial El Rey 195 ml": 18,
      "Salsa Reina El rey 195 ml": 18,
      "Salsa Habanera El Rey 195 ml": 18,
      "Paquete El Rey": 100,
      "Molinillo El Rey 30 g": 95,
      "Tira Entero": 65,
      "Tira Molido": 60,
      "Salsa chiltepin Litro": 50,
      "Salsa Especial Litro": 50,
      "Salsa Reina Litro": 50,
      "Salsa Habanera Litro": 50,
      "Michela Mix Tamarindo": 32,
      "Michela Mix Mango": 32,
      "Michela Mix Sandia": 32,
      "Michela Mix Fuego": 32,
      "Michela Mix Picafresa": 32,
      "El Rey Mix Original": 60,
      "El Rey Mix Especial": 60,
      "Medio Kilo Chiltepin Entero": 600,
      "Habanero Molido 50 g": 40,
      "Habanero Molido 20 g": 20,
      "Molinillo Habanero 20 g": 75,
    },
  },
  pacificTiraMolido: {
    EFT: {
      "Tira Molido": 60,
    },
  },
};

const NORMALIZED_TERRITORY_EMAILS = new Map<string, Set<string>>(
  Object.entries(TERRITORY_SELLER_EMAILS).map(([territory, emails]) => [
    territory,
    new Set(emails.map((email) => email.trim().toLowerCase())),
  ]),
);

const PRICES: ProductPrices = {
  EFT: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  CLEY: {
    "Chiltepin Molido 50 g": 44.16,
    "Chiltepin Molido 20 g": 22.08,
    "Chiltepin Entero 30 g": 46,
    "Salsa Chiltepin El rey 195 ml": 15,
    "Salsa Especial El Rey 195 ml": 15,
    "Salsa Reina El rey 195 ml": 15,
    "Salsa Habanera El Rey 195 ml": 15,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 82.8,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 46,
    "Salsa Especial Litro": 46,
    "Salsa Reina Litro": 46,
    "Salsa Habanera Litro": 46,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  TERE: {
    "Chiltepin Molido 50 g": 45,
    "Chiltepin Molido 20 g": 22.5,
    "Chiltepin Entero 30 g": 40,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 43,
    "Salsa Especial Litro": 43,
    "Salsa Reina Litro": 43,
    "Salsa Habanera Litro": 43,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  BEKOOK: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  OXX: {
    "Chiltepin Molido 50 g": 44.1,
    "Chiltepin Molido 20 g": 22.5,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 15.68,
    "Salsa Especial El Rey 195 ml": 15.68,
    "Salsa Reina El rey 195 ml": 15.68,
    "Salsa Habanera El Rey 195 ml": 15.68,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 58.8,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 40,
    "Salsa Especial Litro": 40,
    "Salsa Reina Litro": 40,
    "Salsa Habanera Litro": 40,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  LAMERA: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  MM: {
    "Chiltepin Molido 50 g": 45,
    "Chiltepin Molido 20 g": 22.5,
    "Chiltepin Entero 30 g": 40,
    "Salsa Chiltepin El rey 195 ml": 14.5,
    "Salsa Especial El Rey 195 ml": 14.5,
    "Salsa Reina El rey 195 ml": 14.5,
    "Salsa Habanera El Rey 195 ml": 14.5,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 85,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 40,
    "Salsa Especial Litro": 40,
    "Salsa Reina Litro": 40,
    "Salsa Habanera Litro": 40,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  FRUTVARELA: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  IZAG: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  ENCANTO: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  BELTR: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  SFACIL: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  FOODS: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  DBCENTRO: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 15,
    "Salsa Especial El Rey 195 ml": 15,
    "Salsa Reina El rey 195 ml": 15,
    "Salsa Habanera El Rey 195 ml": 15,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 40,
    "Salsa Especial Litro": 40,
    "Salsa Reina Litro": 40,
    "Salsa Habanera Litro": 40,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  CASETA: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  KIOSK: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  MERKAHORRO: {
    "Chiltepin Molido 50 g": 45,
    "Chiltepin Molido 20 g": 22.5,
    "Chiltepin Entero 30 g": 40,
    "Salsa Chiltepin El rey 195 ml": 15,
    "Salsa Especial El Rey 195 ml": 15,
    "Salsa Reina El rey 195 ml": 15,
    "Salsa Habanera El Rey 195 ml": 15,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 45,
    "Salsa Especial Litro": 45,
    "Salsa Reina Litro": 45,
    "Salsa Habanera Litro": 45,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  CHATA: {
    "Chiltepin Molido 50 g": 50,
    "Chiltepin Molido 20 g": 25,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 18,
    "Salsa Especial El Rey 195 ml": 18,
    "Salsa Reina El rey 195 ml": 18,
    "Salsa Habanera El Rey 195 ml": 18,
    "Paquete El Rey": 120,
    "Molinillo El Rey 30 g": 105,
    "Tira Entero": 90,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  MEMIN: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 13.6,
    "Salsa Especial El Rey 195 ml": 13.6,
    "Salsa Reina El rey 195 ml": 13.6,
    "Salsa Habanera El Rey 195 ml": 13.6,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 45,
    "Salsa Especial Litro": 45,
    "Salsa Reina Litro": 45,
    "Salsa Habanera Litro": 45,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  QUERI: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  MERZ: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Molinillo Habanero 20 g": 75,
  },
  CRED: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 45,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 90,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  SMART: {
    "Chiltepin Molido 50 g": 52.2733333,
    "Chiltepin Molido 20 g": 26.14,
    "Chiltepin Entero 30 g": 49.955,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 94.09,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 32,
    "Michela Mix Mango": 32,
    "Michela Mix Sandia": 32,
    "Michela Mix Fuego": 32,
    "Michela Mix Picafresa": 32,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 40,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 75,
  },
  WM: {
    "Chiltepin Molido 50 g": 48,
    "Chiltepin Molido 20 g": 24,
    "Chiltepin Entero 30 g": 50,
    "Salsa Chiltepin El rey 195 ml": 16,
    "Salsa Especial El Rey 195 ml": 16,
    "Salsa Reina El rey 195 ml": 16,
    "Salsa Habanera El Rey 195 ml": 16,
    "Paquete El Rey": 100,
    "Molinillo El Rey 30 g": 80,
    "Tira Entero": 60,
    "Tira Molido": 55,
    "Salsa chiltepin Litro": 50,
    "Salsa Especial Litro": 50,
    "Salsa Reina Litro": 50,
    "Salsa Habanera Litro": 50,
    "Michela Mix Tamarindo": 30,
    "Michela Mix Mango": 30,
    "Michela Mix Sandia": 30,
    "Michela Mix Fuego": 30,
    "Michela Mix Picafresa": 30,
    "El Rey Mix Original": 60,
    "El Rey Mix Especial": 60,
    "Habanero Molido 50 g": 42.5,
    "Habanero Molido 20 g": 20,
    "Medio Kilo Chiltepin Entero": 500,
    "Molinillo Habanero 20 g": 70,
  },
};

function normalizeText(value: string): string {
  if (!value) return "";
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\u00ad/g, "")
    .replace(/\u00a0/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

function getTerritoryOverridePrice(
  normalizedCode: string,
  product: string,
  sellerEmail?: string | null,
): number | null {
  const normalizedEmail = (sellerEmail ?? "").trim().toLowerCase();
  if (!normalizedEmail) return null;

  for (const [territory, emailSet] of NORMALIZED_TERRITORY_EMAILS.entries()) {
    if (!emailSet.has(normalizedEmail)) {
      continue;
    }

    const territoryPrices = PRICE_OVERRIDES_BY_TERRITORY[territory];
    const price =
      territoryPrices?.[normalizedCode as "EFT" | "CRED"]?.[product];

    if (price !== undefined) {
      return price;
    }
  }

  return null;
}

export function getProductPrice(
  clientCode: string,
  product: string,
  context?: { clientName?: string; sellerEmail?: string | null },
): number {
  const normalizedCode = clientCode.toUpperCase();
  const priceList = PRICES[normalizedCode] || PRICES.EFT;

  if (
    normalizedCode === "EFT" &&
    context?.clientName &&
    normalizeText(context.clientName).includes("karnemax cedis") &&
    product.startsWith("Michela Mix")
  ) {
    return 32;
  }

  const territoryOverridePrice = getTerritoryOverridePrice(
    normalizedCode,
    product,
    context?.sellerEmail,
  );

  if (territoryOverridePrice !== null) {
    return territoryOverridePrice;
  }

  const price = priceList[product];

  if (price === undefined || price === 0) {
    console.warn("PRICE ISSUE:", {
      clientCode: normalizedCode,
      product,
      price: price ?? "undefined",
      hasPriceList: !!PRICES[normalizedCode],
      availableProducts: priceList ? Object.keys(priceList).length : 0,
      timestamp: new Date().toISOString(),
    });
  }

  return price || 0;
}
